### ISSUE TITLE
Error with nsp check,

### ISSUE THREAD

**Issue by smavanga** [coryhouse/javascript-development-environment#26]
After following all the details on your repository, I got a lot of warnings that all versions of rpm are deprecated and by run the nsp check command I got the same error I got after setting my environment so I can't start my browser to see all results, please help because this course is so exciting to follow, 
$ nsp check
(+) Client request error: getaddrinfo ENOTFOUND api.nodesecurity.io api.nodesecurity.io:443

**Comment by coryhouse** [comment]
Hi - You can omit the nsp step since security checks are now built into npm. (I added callouts to the corresponding clips in the course, so perhaps you overlooked them?) Once you complete the course, I've shown how to upgrade the final demo to use the latest versions here: https://github.com/coryhouse/javascript-development-environment/pull/7
